services:
    app.admin.order:
        class: AppBundle\Admin\OrderAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Shop", label: "Orders" }
        arguments:
            - ~
            - AppBundle\Entity\Order
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]

    app.admin.image:
        class: AppBundle\Admin\ImageAdmin
        arguments: [~, AppBundle\Entity\Image, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Images, label: Image }
